###############################################################
# Program:
#     Assignment 09, Binary Search Tree
#     Brother JonesL, CS235
# Author:
#     Maximiliano Correa, Esteban Cabrera and Tony Moraes
# Summary:
#     We try to make the 4 tests but that assignment show to be more
# complicated. 
# Time:
#     5 days.
###############################################################

##############################################################
# The main rule
##############################################################
a.out: assignment09.o
	g++ -o a.out assignment09.o -g -std=c++11
	tar -cf assignment09.tar *.h *.cpp makefile

##############################################################
# The individual components
#      assignment09.o     : the driver program
##############################################################
assignment09.o: bst.h assignment09.cpp
	g++ -c assignment09.cpp -g -std=c++11

